### ISSUE TITLE
实在不明白 child 里面是div ，是如何把input onchange事件绑定到form里面来的

### ISSUE THREAD

**Issue by nearxu** [varHarrie/react-hero#3]
我自己的思路是input onChange事件做一个dispatch，通过reduce进行分发，可是这样就没有办法做到定制化，麻烦作者稍微讲讲思路，万分感谢。

**Comment by varHarrie** [comment]
我们平常使用受控组件的时候，是自己维护一个`value`状态和`onChange`事件：

```javascript
class App extends React.Component {
  constructor (props) {
    super(props)

    // 状态
    this.state = {
      value: ''
    }
  }

  // 事件
  onChange = (e) => {
    this.setState({value: e.target.value})
  }

  render () {
    const { value } = this.state
    return (
      <input value={value} onChange={this.onChange}/>
    )
  }
}
```

而这里的实现方式是，`value`和`onChange`都由`FormField`去维护，因为`input`组件是作为`children`传入，我们这里可以通过`React.cloneElement`去修改`children`的`props`，即传入`value`和`onChange`，详细看[这里](https://github.com/varHarrie/react-hero/blob/master/packages/form/src/FormItem.tsx#L33)。

这里有一篇[文章](https://github.com/varHarrie/varharrie.github.io/issues/28)详细说明了实现思路。

**Comment by nearxu** [comment]
非常感谢，已经解决了，不过这个react.cloneElement 方法太隐蔽了
